FROM golang AS builder
WORKDIR /app
COPY . .
RUN ls
RUN CGO_ENABLED=0 GOOS=linux go build -o arrays -ldflags '-extldflags "-static"' .

FROM builder AS run-tests
RUN go test -v ./...
RUN go test -bench=. ./...

FROM scratch
COPY --from=builder /app /
CMD ["arrays"]
